services:
  - type: web
    name: tn-streaming
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: 3fd2be6f0c70a2a598f084ddfb75487c
        sync: false
      - key: CORS_ORIGIN
        value: '*'
    pullRequestPreviewsEnabled: false
    autoDeploy: true
