services:
  - type: web
    name: tn-streaming
    runtime: static
    buildCommand: echo "TNSTREAMING static site ready"
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    autoDeploy: true
